export const DISPLAY_ALERT = "SHOW_ALERT";
export const CLEAR_ALERT = "CLEAR_ALERT";

export const SETUP_USER_BEGIN = 'LOGIN_USER_BEGIN';
export const SETUP_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const SETUP_USER_ERROR = 'LOGIN_USER_ERROR';

export const GET_CURRENT_USER_BEGIN = "GET_CURRENT_USER_BEGIN";
export const GET_CURRENT_USER_SUCCESS = "GET_CURRENT_USER_SUCCESS";

export const UPDATE_USER_BEGIN = "UPDATE_USER_BEGIN";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_ERROR = "UPDATE_USER_ERROR";

export const LOGOUT_USER = "LOGOUT_USER";

export const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR";

export const HANDLE_CHANGE = "HANDLE_CHANGE";

export const CLEAR_VALUES = "CLEAR_VALUES";


export const CREATE_EXP_BEGIN = "CREATE_EXP_BEGIN";
export const CREATE_EXP_SUCCESS = "CREATE_EXP_SUCCESS";
export const CREATE_EXP_ERROR = "CREATE_EXP_ERROR";

export const GET_EXP_BEGIN = "GET_EXP_BEGIN";
export const GET_EXP_SUCCESS = "GET_EXP_SUCCESS";

export const SET_EDIT_EXP = "SET_EDIT_EXP";

export const EDIT_EXP_BEGIN = "EDIT_EXP_BEGIN";
export const EDIT_EXP_SUCCESS = "EDIT_EXP_SUCCESS";
export const EDIT_EXP_ERROR = "EDIT_EXP_ERROR";


export const DELETE_EXP_BEGIN = "DELETE_EXP_BEGIN";

export const SHOW_STATS_BEGIN = "SHOW_STATS_BEGIN";
export const SHOW_STATS_SUCCESS = "SHOW_STATS_SUCCESS";

export const CLEAR_FILTERS = "CLEAR_FILTERS";

export const CHANGE_PAGE = "CHANGE_PAGE";